### ISSUE TITLE
kinetic basestation error tables missing

### ISSUE THREAD

**Issue by allotmentandy** [varnav/BaseStation.sqb#1]
hi, i tried to use this with the Kinetic SBS Basestation spotting rader software, but it errors with a missing table.

is this something i can fix myself? i would love to use your sqb file, but not sure how to fix it.

any ideas?

**Comment by varnav** [comment]
It seems that this app needs some other variant of BaseStation.sqb with much more tables. This one won't work.

**Comment by allotmentandy** [comment]
yes, i have found a basestation.sqb on the radarspotting website which has about 5 other tables in it.

thanks for your time

**Comment by allotmentandy** [comment]
can i just ask what is the point of your basestation.sqb file? what software do you use it with?

**Comment by varnav** [comment]
This: https://github.com/szpajder/dumpvdl2
